services:
  admin-web:
    container_name: admin-web-ui
    build:
      context: ../services/admin-web-ui
    networks:
      - frontend
    ports:
      - "5173:5173"
  
  user-web:
    container_name: user-web-ui
    build:
      context: ../services/user-web-ui
    networks:
      - frontend
    ports:
      - "5174:5174"

  user-app:
    container_name: user-app
    build:
      context: ../services/user-app
    networks:
      - frontend
    environment:
      - EXPO_PACKAGER_OPTS=--tunnel
      - EXPO_TUNNEL=true
    stdin_open: true
    tty: true
    
  api:
    container_name: api
    build:
      context: ../services/rest-api
    networks:
      - backend
      - frontend
    volumes:
      - ../services/db:/db
      - ../services/bike-logic:/bike-logic
    ports:
      - "1337:1337"

networks:
  frontend:
  backend:
